name: ZenANN CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install toolchain & deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            g++ \
            ninja-build \
            libopenblas-dev \
            libomp-dev \
            python3-dev
        pip install pybind11 pytest

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Build Faiss (CPU-only)
      working-directory: extern/faiss
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_INSTALL_PREFIX="${PWD}/build/install" \
          -DFAISS_ENABLE_PYTHON=OFF \
          -DFAISS_ENABLE_TESTING=OFF \
          -DFAISS_ENABLE_GPU=OFF \
          -DFAISS_ENABLE_CUDA=OFF \
          -DBLAS_LIBRARIES=openblas                 
        cmake --build build -j"$(nproc)"
        cmake --install build

    - name: Build ZenANN module
      env:
        FAISS_INC: extern/faiss/build/install/include
        FAISS_LIB: extern/faiss/build/install/lib     
      run: |
        make
        
    - name: Run unit-tests
      run: |
        pytest tests/
